arrLang = {
  EN: {
    "header-catalog": "catalog",
    "header-about": "about",
    "header-blog": "blog",
    "header-faq": "faq",
    "header-clothes": "clothes",
    "header-t-shirt": "T-shirt",
    "header-sweatshirts": "Sweatshirts",
    "header-trousers": "Trousers",
    "header-outerwear": "Outerwear",
    "header-shoes": "Shoes",
    "header-boots": "Boots",
    "header-sneakers": "Sneakers",
    "header-gumshoes": "Gumshoes",
    "header-slippers": "Slippers",
    "header-placeholder-search": "Search for products and more",
    "header-welcome": "Hello,",
    "header-myprofile": "My profile",
    "header-editprofile": "Edit profile",
    "header-myorders": "My Order",
    "header-mycart": "My cart",
    "header-mywishlist": "My wishlist",
    "header-exitaccount": "Logout",
    "header-account": "Account",
    "breadcrumbs-home": "Home",
    "breadcrumbs-auth": "Authorization and Registration",
    "breadcrumbs-myaccount": "My Profile",
    "breadcrumbs-catalog": "Catalog",
    "breadcrumbs-search": "Search",
    "breadcrumbs-about": "About",
    "breadcrumbs-faq": "FAQ",
    "breadcrumbs-blog": "Blog",
    "auth-signup-title": "Create Account",
    "auth-placeholder-email": "Email",
    "auth-placeholder-password": "Password",
    "auth-placeholder-firstname": "First Name",
    "auth-placeholder-lastname": "Last Name",
    "auth-placeholder-dateofbirth": "Date of birth",
    "auth-placeholder-address": "Address",
    "auth-signup-btn": "Sign Up",
    "auth-signin-title": "Sign In",
    "auth-signin-btn": "Sign In",
    "auth-signin-overlay-title": "Welcome Back!",
    "auth-signin-overlay-subtitle":
      "To keep connected with us please login with your personal info",
    "auth-signup-overlay-title": "Hello, Friend!",
    "auth-signup-overlay-subtitle":
      "Enter your personal details and start journey with us",
    "profile-title": "Hi,",
    "profile-account-overview": "Account overview",
    "profile-mydetails": "My Details",
    "profile-myorders": "My Order",
    "profile-mycart": "My cart",
    "profile-mywishlist": "My wishlist",
    "profile-logout": "Logout",
    "profile-accout-overview-titlstart": "welcome to",
    "profile-accout-overview-titlend": "your account",
    "profile-mydetails-text":
      "Feel free to edit any of your details below so your <b>LIAPARO</b> account is totally up to date.",
    "profile-mydetails-firstname": "Firstname",
    "profile-mydetails-lastname": "Lastname",
    "profile-mydetails-email": "Email",
    "profile-mydetails-dateofbirth": "Dateofbirth",
    "profile-mydetails-address": "Address",
    "profile-mydetails-btn-savechanges": "Save Changes",
    "profile-myorders-allamount": "Amount to all orders:",
    "profile-mycart-fullprice": "Full Price",
    "profile-mycart-btn-clearall": "Clear all",
    "profile-mycart-btn-checkout": "Checkout",
    "company-benefits-itemone":
      "The company specialists annually take special training courses, attend seminars, go on internships, participate in conferences and so on.",
    "company-benefits-itemtwo":
      "The quality of our products is so high that we almost do not spend money on advertising, people find us themselves.",
    "company-benefits-itemthree":
      "Our employees receive free trips, soft loans and other benefits, and therefore hold on to the place and work in good faith.",
    "company-benefits-itemfour":
      "Over the past years, the company's net profit has been increasing annually by 25% due to: optimization of production, improving the quality of service.",
    "single-product-review": "Reviews",
    "single-product-review-btn-send": "Send",
    "single-product-btn-addtocart": "Add to Cart",
    "single-product-btn-wishlist": "Wishlist",
    "single-product-about-product": "About Product",
    "single-product-description": "Description",
    "single-product-composition": "Composition",
    "single-product-color": "Color",
    "single-product-country": "Country",
    "sale-slider-title": "Sale",
    "catalog-filter": "Filters",
    "catalog-filter-clearall": "Clear all",
    "catalog-filter-type": "Type:",
    "catalog-filter-type-all": "All",
    "catalog-filter-type-clothes": "Clothes",
    "catalog-filter-type-shoes": "Shoes",
    "catalog-filter-sybtype-clothes": "Subtype:",
    "catalog-filter-subtype-clothes-all": "All",
    "catalog-filter-subtype-clothes-tshirt": "T-shirt",
    "catalog-filter-subtype-clothes-sweatshirts": "Sweatshirts",
    "catalog-filter-subtype-clothes-trousers": "Trousers",
    "catalog-filter-subtype-clothes-outerwear": "Outerwear",
    "catalog-filter-subtype-shoes": "Subtype:",
    "catalog-filter-subtype-shoes-all": "All",
    "catalog-filter-subtype-shoes-boots": "Boots",
    "catalog-filter-subtype-shoes-sneakers": "Sneakers",
    "catalog-filter-subtype-shoes-gumshoes": "Gumshoes",
    "catalog-filter-subtype-shoes-slippers": "Slippers",
    "catalog-filter-brand": "Brand:",
    "catalog-filter-brand-all": "All",
    "catalog-filter-color": "Color:",
    "catalog-filter-color-all": "All",
    "catalog-filter-color-black": "Black",
    "catalog-filter-color-white": "White",
    "catalog-filter-color-gray": "Gray",
    "catalog-filter-color-blue": "Blue",
    "catalog-filter-color-darkblue": "Dark blue",
    "catalog-filter-color-red": "Red",
    "catalog-filter-color-green": "Green",
    "catalog-filter-color-yellow": "Yellow",
    "catalog-filter-country": "Country:",
    "catalog-filter-country-all": "All",
    "catalog-filter-country-india": "India",
    "catalog-filter-country-tyrkey": "Tyrkey",
    "catalog-filter-country-vietnam":"Vietnam",
    "catalog-filter-country-columbia":"Columbia",
    "catalog-filter-price": "Price:",
    "catalog-filter-price-placeholder-to": "to",
    "catalog-filter-price-placeholder-from": "from",
    "catalog-filter-btn-search": "Search",
    "catalog-sort": "Sort by",
    "catalog-sort-default": "Recommended",
    "catalog-sort-hightolow": "Price: High to Low",
    "catalog-sort-lowtohigh": "Price:Low to High",
    "catalog-btn-addtocart": "Add to Cart",
    "catalog-btn-moredetails": "More Details",
    "catalog-btn-wishlist": "Wishlist",
    "chat-bot-phrase-one": "Hello! My name is Alice!",
    "chat-bot-phrase-two": "What is your name?",
    "chat-bot-phrase-three-dot-one": "Nice to meet you",
    "chat-bot-phrase-three-dot-two":
      "You don’t want to say your name, well, stay anonymous.",
    "chat-bot-phrase-four": "May I help you?",
    "chat-bot-phrase-four-yes": "Yes.",
    "chat-bot-phrase-four-no": "No, thanks.",
    "chat-bot-phrase-five-dot-one":
      "Sorry, but at this point in time, my AI will not be able to do anything (((( *Cry*cry*",
    "chat-bot-phrase-five-dot-two": "Ok!All the bests.",
    "chat-bot-answer-one-yes": "Yes.",
    "chat-bot-answer-one-no": "No.",
    "chat-bot-placeholder-inputmessage": "Enter message...",
    "chat-bot-consultant": "Cosultant AI",
    "placeholder-search": "Search for products and more",
    // "search-results": "Nothing found for your request",
    "about-contact": "Contacts",
    "about-contact-title-one":
      "For all questions you can contact us in a convenient way:",
    "about-contact-title-two": "By phone:",
    "about-contact-title-three": "On social networks and online:",
    "about-map": "We are on the map:",
    "about-content-sitename": "LIAPARO",
    "about-content-info":
      "— the largest clothing store in Belarus with the widest assortment and competitive prices.",
    "about-content-info-extra":
      "Here shoppers are provided with comfortable, affordable and safe online shopping.",
    "footer-contact": "Contacts:",
    "footer-social": "Socials:",
    "order-product-amount": "Count:",
    "order-product-price-text-after": "products",
    "order-product-price-text-before": "for",
    "dialog-message": "The user does not exist, check the entered data.",
    "dialog-title": "Error",
    "dialog-close": "Close",
    "faq-accordion-title-one": "How to change personal data in the store’s office?",
    "faq-accordion-title-two": "What is a store account?",
    "faq-accordion-title-three": "Why should I register as a buyer?",
    "faq-accordion-text-one":
      "To change personal data, go to the company’s office under with your username and password, go to the «My Profile -> my Details».",
    "faq-accordion-text-two":
      "The store’s office is a «control panel» for your goods and personal information. A company account is created automatically upon registration at LIAPARO.",
    "faq-accordion-text-three":
      "After registering as a buyer, the customer’s office will appear on the portal. Buyer's office features: placing orders, the ability to monitor the status of fulfillment of orders, storing order history, the ability to correspond with our consultants and message exchange history, quickly adding reviews."
  
  },
  RU: {
    "header-catalog": "Каталог",
    "header-about": "О нас",
    "header-blog": "Блог",
    "header-faq": "Faq",
    "header-clothes": "Одежда",
    "header-t-shirt": "Футболки",
    "header-sweatshirts": "Толстовки",
    "header-trousers": "Штаны",
    "header-outerwear": "Верхняя одежда",
    "header-shoes": "Обувь",
    "header-boots": "Ботинки",
    "header-sneakers": "Кроссовки",
    "header-gumshoes": "Кеды",
    "header-slippers": "Тапочки",
    "header-placeholder-search": "Поиск товаров и многое другое",
    "header-welcome": "Привет,",
    "header-myprofile": "Профиль",
    "header-editprofile": "Изменить",
    "header-myorders": "Заказы",
    "header-mycart": "Корзина",
    "header-mywishlist": "Избранное",
    "header-exitaccount": "Выход",
    "header-account": "Аккаунт",
    "breadcrumbs-home": "Главная",
    "breadcrumbs-auth": "Авторизация и регистрация",
    "breadcrumbs-myaccount": "Профиль",
    "breadcrumbs-catalog": "Каталог",
    "breadcrumbs-search": "Поиск",
    "breadcrumbs-about": "О нас",
    "breadcrumbs-faq": "FAQ",
    "breadcrumbs-blog": "Блог",
    "auth-signup-title": "Создать аккаунт",
    "auth-placeholder-email": "Почта",
    "auth-placeholder-password": "Пароль",
    "auth-placeholder-firstname": "Имя",
    "auth-placeholder-lastname": "Фамилия",
    "auth-placeholder-dateofbirth": "Дата рождения",
    "auth-placeholder-address": "Адрес",
    "auth-signup-btn": "Зарегистрироваться",
    "auth-signin-title": "Вход",
    "auth-signin-btn": "Войти",
    "auth-signin-overlay-title": "Добро пожаловать назад!",
    "auth-signin-overlay-subtitle":
      "Чтобы оставаться на связи с нами, пожалуйста, войдите в ваш аккаунт",
    "auth-signup-overlay-title": "Привет друг!",
    "auth-signup-overlay-subtitle":
      "Введите свои личные данные и начните путешествие с нами",
    "profile-title": "Привет,",
    "profile-account-overview": "Обзор аккаунта",
    "profile-mydetails": "Личная информация",
    "profile-myorders": "Заказы",
    "profile-mycart": "Корзина",
    "profile-mywishlist": "Избранное",
    "profile-logout": "Выход",
    "profile-accout-overview-titlstart": "Welcome to",
    "profile-accout-overview-titlend": "your account",
    "profile-mydetails-text":
      "Не стесняйтесь редактировать любые свои данные ниже, чтобы ваша аккаунт на <b> LIAPARO </b> был всегда актуален.",
    "profile-mydetails-firstname": "Имя",
    "profile-mydetails-lastname": "Фамилия",
    "profile-mydetails-email": "Почта",
    "profile-mydetails-dateofbirth": "Дата рожденя",
    "profile-mydetails-address": "Адрес",
    "profile-mydetails-btn-savechanges": "Сохранить изменения",
    "profile-myorders-allamount": "Общая сумма всех заказов:",
    "profile-mycart-fullprice": "Общая цена",
    "profile-mycart-btn-clearall": "Очистить",
    "profile-mycart-btn-checkout": "Оплатить",
    "company-benefits-itemone":
      "Специалисты компании ежегодно проходят специальные учебные курсы, посещают семинары, проходят стажировки, участвуют в конференциях",
    "company-benefits-itemtwo":
      "Качество нашей продукции настолько высоко, что мы практически не тратим деньги на рекламу, люди сами находят нас.",
    "company-benefits-itemthree":
      "Наши сотрудники получают бесплатные поездки, льготные кредиты и другие льготы, поэтому держатся за свое место и работают добросовестно.",
    "company-benefits-itemfour":
      "За последние годы чистая прибыль компании ежегодно увеличивалась на 25% за счет: оптимизации производства, повышения качества обслуживания.",
    "single-product-review": "Отзывы",
    "single-product-review-btn-send": "Оставить",
    "single-product-btn-addtocart": "в корзину",
    "single-product-btn-wishlist": "в избранное",
    "single-product-about-product": "О товаре",
    "single-product-description": "Описание",
    "single-product-composition": "Состав",
    "single-product-color": "Цвет",
    "single-product-country": "Страна",
    "sale-slider-title": "Скидка",
    "catalog-filter": "Фильтры",
    "catalog-filter-clearall": "Очистить",
    "catalog-filter-type": "Категория:",
    "catalog-filter-type-all": "Все",
    "catalog-filter-type-clothes": "Одежда",
    "catalog-filter-type-shoes": "Обувь",
    "catalog-filter-sybtype-clothes": "Вид:",
    "catalog-filter-subtype-clothes-all": "Все",
    "catalog-filter-subtype-clothes-tshirt": "Футболки",
    "catalog-filter-subtype-clothes-sweatshirts": "Толстовки",
    "catalog-filter-subtype-clothes-trousers": "Штаны",
    "catalog-filter-subtype-clothes-outerwear": "Верхняя одежда",
    "catalog-filter-subtype-shoes": "Вид:",
    "catalog-filter-subtype-shoes-all": "Все",
    "catalog-filter-subtype-shoes-boots": "Ботинки",
    "catalog-filter-subtype-shoes-sneakers": "Кроссовки",
    "catalog-filter-subtype-shoes-gumshoes": "Кеды",
    "catalog-filter-subtype-shoes-slippers": "Тапочки",
    "catalog-filter-brand": "Бренд:",
    "catalog-filter-brand-all": "Все",
    "catalog-filter-color": "Цвет:",
    "catalog-filter-color-all": "Все",
    "catalog-filter-color-black": "Черный",
    "catalog-filter-color-white": "Белый",
    "catalog-filter-color-gray": "Серый",
    "catalog-filter-color-blue": "Синий",
    "catalog-filter-color-darkblue": "Темно-синий",
    "catalog-filter-color-red": "Красный",
    "catalog-filter-color-green": "Зеленый",
    "catalog-filter-color-yellow": "Желтый",
    "catalog-filter-country": "Страна:",
    "catalog-filter-country-all": "Все",
    "catalog-filter-country-india": "Индия",
    "catalog-filter-country-tyrkey": "Турция",
    "catalog-filter-country-vietnam":"Вьетнам",
    "catalog-filter-country-columbia":"Колумбия",
    "catalog-filter-price": "Цена:",
    "catalog-filter-price-placeholder-to": "до",
    "catalog-filter-price-placeholder-from": "от",
    "catalog-filter-btn-search": "Найти",
    "catalog-sort": "Сортировка",
    "catalog-sort-default": "Рекомендуется",
    "catalog-sort-hightolow": "Цена: по убыванию",
    "catalog-sort-lowtohigh": "Цена: по возрастанию",
    "catalog-btn-addtocart": "В корзину",
    "catalog-btn-moredetails": "Подробнее",
    "catalog-btn-wishlist": "В избранное",
    "chat-bot-phrase-one": "Привет! Меня зовут Алиса!",
    "chat-bot-phrase-two": "А вас как зовут?",
    "chat-bot-phrase-three-dot-one": "Приятно познакомится",
    "chat-bot-phrase-three-dot-two":
      "Не хотите говорить свое имя, ну ладно оставайтесь анонимом.",
    "chat-bot-phrase-four": "Я могу чем-нибудь помочь?",
    "chat-bot-phrase-four-yes": "Да.",
    "chat-bot-phrase-four-no": "Нет, спасибо.",
    "chat-bot-phrase-five-dot-one":
      "Извините, но на данный момент мой ИИ не сможет ничем помочь(((( *Плак**Плак*",
    "chat-bot-phrase-five-dot-two": "Хорошо! Всего наилучшего.",
    "chat-bot-answer-one-yes": "Да.",
    "chat-bot-answer-one-no": "Нет.",
    "chat-bot-placeholder-inputmessage": "Введите сообщение...",
    "chat-bot-consultant": "Консультант ИИ",
    "placeholder-search": "Поиск товаров и многое другое",
    // "search-results": "По вашему запросу ничего не найдено",
    "about-contact": "Контакты",
    "about-contact-title-one":
      "По всем вопросам Вы можете связаться с нами удобным способом:",
    "about-contact-title-two": "по телефону:",
    "about-contact-title-three": "В социальных сетях и онлайн:",
    "about-map": "Мы на карте:",
    "about-content-sitename": "LIAPARO",
    "about-content-info":
      "— крупнейший магазин одежды Беларуси с широчайшим ассортиментом и выгодными ценами.",
    "about-content-info-extra":
      "Здесь покупатели обеспечены комфортным, доступным и безопасным онлайн-шопингом.",
    "footer-contact": "Контакты:",
    "footer-social": "Социальные сети:",
    "order-product-amount": "Кол-во:",
    "order-product-price-text-after": "товара",
    "order-product-price-text-before": "за",
    "dialog-message": "Пользователя не существует, проверьте введенные данные.",
    "dialog-title": "Ошибка",
    "dialog-close": "Закрыть",
    "faq-accordion-title-one": "Как изменить личных данных в кабинет магазина?",
    "faq-accordion-title-two": "Что такое кабинет магазина?",
    "faq-accordion-title-three": "Зачем мне регистрироваться как покупатель?",
    "faq-accordion-text-one":
      "Для изменения личных данных, зайдите в кабинет компании под со своим логином и паролем, перейдите в раздел «Профиль --> Личная информация».",
    "faq-accordion-text-two":
      "Кабинет магазина — это «панель управления» вашими товарами и личной информацией. Кабинет компании создаётся автоматически при регистрации на LIAPARO.",
    "faq-accordion-text-three":
      " После регистрации в качестве покупателя на портале у вас появится кабинет покупателя.Возможности кабинета покупателя: оформление заказов, возможность следить за статусами выполнения своих заказовб хранение истории заказов, возможность вести переписку с нашими консульатнтами и историю обмена сообщений, быстрое добавление отзывов."
  }
};
